services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 50 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health